title: James Dargan
logo: "/images/Circle_Profile.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2 style="text-align:center"> Aspiring Data Scientist </h2>
  <h5 style="text-align:center"> Seattle, WA </h5>
  <h3>
  Actively searching
  <a href="https://www.linkedin.com/in/jamesdargan/">
  <img border="0" img src="/images/LI-In-Bug.png" width="25" height="20"></a>
  <a href="mailto:james.j.dargan@gmail.com">
  <img border="0" img src="/images/gmail.png" width="30" height="20"></a>
  </h3><br>

  <h4> Technical Skills </h4>
  <p style="font-size:12px">
    Languages: Python, SQL, R <br>
    Stats: Experiment Design, A/B Test, Probability <br>
    Modeling: Regression, PCA, Trees, RFs, SVMs, Boosting, Neural Networks <br>
  </p>


  <h4> Python Experience </h4>
  <p style="font-size:12px">
    Scrape: Beautiful Soup, Requests, APIs <br>
    Visualization: Seaborn, Plotly, Dash <br>
    Machine Learning: scikit-learn, keras <br>
    Misc: Pandas, nltk, GridSearch, Pipeline
  </p>


theme: jekyll-theme-minimal
