title: James Dargan
logo: "/images/Circle_Profile.png?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h2 style="text-align:center"> Aspiring Data Scientist </h2>
  <h5 style="text-align:center"> Seattle, WA <br>
  Python, SQL, R </h5>
  <h3>
  Actively searching
  <a href="https://www.linkedin.com/in/jamesdargan/">
  <img border="0" img src="/images/LI-In-Bug.png" width="25" height="20"></a>
  <a href="mailto:james.j.dargan@gmail.com">
  <img border="0" img src="/images/gmail.png" width="30" height="20"></a>
  </h3><br>

  <p style="font-size:12px">
  Pandas, BeautifulSoup, Requests, Plotly, Dash, nltk, Sklearn, Keras <br>
  Regression, PCA, Time Series, Trees, RFs, SVMs, Boosting, Neural Networks
  </p>


theme: jekyll-theme-minimal
